//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.08 at 10:32:09 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://annamalai.kumaran/Request")
package com.example.springboot.requestxsd;
